/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_17_renan;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author renan_8tvcd4n
 */
public class Atualiza_cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Atualiza_cadastro
     */
    public Atualiza_cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jbtn_Editar = new javax.swing.JButton();
        Jlbl_CPF = new javax.swing.JLabel();
        Jlbl_Tel = new javax.swing.JLabel();
        Jtxtf_Tel = new javax.swing.JTextField();
        Jtxtf_Sobrenome = new javax.swing.JTextField();
        Jtxtf_CPF = new javax.swing.JTextField();
        Jtxtf_Nome = new javax.swing.JTextField();
        Jlbl_nome = new javax.swing.JLabel();
        Jlbl_Sobrenome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Jtxtf_Consulta_FuncionarioByID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jbtn_Editar.setBackground(new java.awt.Color(255, 255, 204));
        Jbtn_Editar.setForeground(new java.awt.Color(0, 0, 0));
        Jbtn_Editar.setText("Editar");
        Jbtn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_EditarActionPerformed(evt);
            }
        });

        Jlbl_CPF.setText("CPF:");

        Jlbl_Tel.setText("Telefone:");

        Jtxtf_Tel.setPreferredSize(new java.awt.Dimension(200, 30));

        Jtxtf_Sobrenome.setPreferredSize(new java.awt.Dimension(200, 30));

        Jtxtf_CPF.setPreferredSize(new java.awt.Dimension(200, 30));

        Jtxtf_Nome.setPreferredSize(new java.awt.Dimension(200, 30));

        Jlbl_nome.setText("Nome:");

        Jlbl_Sobrenome.setText("Sobrenome:");

        jLabel1.setText("Atualizar Cadastro");

        Jtxtf_Consulta_FuncionarioByID.setText("ID");
        Jtxtf_Consulta_FuncionarioByID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxtf_Consulta_FuncionarioByIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(Jbtn_Editar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(233, 233, 233))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jlbl_nome)
                                .addGap(34, 34, 34)
                                .addComponent(Jtxtf_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Jlbl_Sobrenome)
                                    .addComponent(Jlbl_CPF))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Jtxtf_Sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jtxtf_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Jlbl_Tel)
                                .addGap(22, 22, 22)
                                .addComponent(Jtxtf_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Jtxtf_Consulta_FuncionarioByID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(170, 170, 170))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlbl_nome)
                    .addComponent(Jtxtf_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlbl_Sobrenome)
                    .addComponent(Jtxtf_Sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jlbl_CPF)
                    .addComponent(Jtxtf_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlbl_Tel)
                    .addComponent(Jtxtf_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Jtxtf_Consulta_FuncionarioByID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(Jbtn_Editar)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_EditarActionPerformed
        // TODO add your handling code here:
        Connection connection = null;
        PreparedStatement statement = null;
        String url = "jdbc:mysql://localhost:3306/projeto18";
        String user = "root";
        String psswrd = "";

        try {
            connection = DriverManager.getConnection(url, user, psswrd);
            String query = "UPDATE instrutor SET nome = ?, sobrenome = ?, CPF = ?, telefone = ? WHERE id_instrutor = ?";
            statement = connection.prepareStatement(query);

            statement.setString(1, Jtxtf_Nome.getText());
            statement.setString(2, Jtxtf_Sobrenome.getText());
            statement.setString(3, Jtxtf_CPF.getText());
            statement.setString(4, Jtxtf_Tel.getText());
            statement.setString(5, Jtxtf_Consulta_FuncionarioByID.getText());
            statement.executeUpdate();

            System.out.println("Cadastro Atualizado!");
        } catch (SQLException erro) {
            System.out.println("Erro: " + erro.getMessage());
        }
    }//GEN-LAST:event_Jbtn_EditarActionPerformed

    private void Jtxtf_Consulta_FuncionarioByIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxtf_Consulta_FuncionarioByIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxtf_Consulta_FuncionarioByIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Atualiza_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Atualiza_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Atualiza_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Atualiza_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Atualiza_cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_Editar;
    private javax.swing.JLabel Jlbl_CPF;
    private javax.swing.JLabel Jlbl_Sobrenome;
    private javax.swing.JLabel Jlbl_Tel;
    private javax.swing.JLabel Jlbl_nome;
    private javax.swing.JTextField Jtxtf_CPF;
    private javax.swing.JTextField Jtxtf_Consulta_FuncionarioByID;
    private javax.swing.JTextField Jtxtf_Nome;
    private javax.swing.JTextField Jtxtf_Sobrenome;
    private javax.swing.JTextField Jtxtf_Tel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
