/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_17_renan;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author renan_8tvcd4n
 */
public class Consulta_Funcionario extends javax.swing.JFrame {

    /**
     * Creates new form Consulta_Funcionario
     */
    public Consulta_Funcionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jbtn_Pesquisar = new javax.swing.JButton();
        Jtxtf_Consulta_FuncionarioByID = new javax.swing.JTextField();
        Jlbl_Nome = new javax.swing.JLabel();
        Jlbl_CPF = new javax.swing.JLabel();
        Jlbl_Tel = new javax.swing.JLabel();
        Jtxtf_Retorno_Nome = new javax.swing.JTextField();
        Jtxtf_Retorno_Tel = new javax.swing.JTextField();
        Jtxtf_Retorno_CPF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jbtn_Pesquisar.setText("Pesquisar");
        Jbtn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_PesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 25, -1, -1));

        Jtxtf_Consulta_FuncionarioByID.setText("ID para Pesquisar");
        Jtxtf_Consulta_FuncionarioByID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxtf_Consulta_FuncionarioByIDActionPerformed(evt);
            }
        });
        getContentPane().add(Jtxtf_Consulta_FuncionarioByID, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 25, 270, -1));

        Jlbl_Nome.setText("Nome:");
        getContentPane().add(Jlbl_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        Jlbl_CPF.setText("CPF:");
        getContentPane().add(Jlbl_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 202, -1, -1));

        Jlbl_Tel.setText("Telefone:");
        getContentPane().add(Jlbl_Tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 238, -1, -1));

        Jtxtf_Retorno_Nome.setPreferredSize(new java.awt.Dimension(200, 30));
        Jtxtf_Retorno_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxtf_Retorno_NomeActionPerformed(evt);
            }
        });
        getContentPane().add(Jtxtf_Retorno_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 256, -1));

        Jtxtf_Retorno_Tel.setPreferredSize(new java.awt.Dimension(200, 30));
        Jtxtf_Retorno_Tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxtf_Retorno_TelActionPerformed(evt);
            }
        });
        getContentPane().add(Jtxtf_Retorno_Tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 231, -1, -1));

        Jtxtf_Retorno_CPF.setPreferredSize(new java.awt.Dimension(200, 30));
        Jtxtf_Retorno_CPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtxtf_Retorno_CPFActionPerformed(evt);
            }
        });
        getContentPane().add(Jtxtf_Retorno_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 195, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jtxtf_Retorno_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxtf_Retorno_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxtf_Retorno_NomeActionPerformed

    private void Jtxtf_Retorno_TelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxtf_Retorno_TelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxtf_Retorno_TelActionPerformed

    private void Jtxtf_Retorno_CPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxtf_Retorno_CPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxtf_Retorno_CPFActionPerformed

    private void Jbtn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_PesquisarActionPerformed
        // TODO add your handling code here:
        Connection connection = null;
        PreparedStatement statement = null;
        String url = "jdbc:mysql://localhost:3306/projeto18";
        String user = "root";
        String psswrd = "";
        
        try {
            connection = DriverManager.getConnection(url, user, psswrd);
            String query = "SELECT nome, sobrenome, CPF, telefone FROM instrutor WHERE id_funcionario = ?";
            statement = connection.prepareStatement(query);
            
            statement.setString(1, Jtxtf_Consulta_FuncionarioByID.getText());
            statement.executeUpdate();
            
            ResultSet resultSet = statement.executeQuery();
            if (resultSet.next()){
                Jtxtf_Retorno_Nome.setText(resultSet.getString("nome") + " " + resultSet.getString("Sobrenome"));
                Jtxtf_Retorno_CPF.setText(resultSet.getString("CPF"));
                Jtxtf_Retorno_Tel.setText(resultSet.getString("telefone"));
                
            }
            else {
                Jtxtf_Retorno_Nome.setText("Instrutor não encontrado!");
            }
            
            System.out.println("Consulta Realizada!");
            
        } catch (SQLException erro){
            System.out.println("Erro: " + erro.getMessage());
        }
    }//GEN-LAST:event_Jbtn_PesquisarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void Jtxtf_Consulta_FuncionarioByIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtxtf_Consulta_FuncionarioByIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtxtf_Consulta_FuncionarioByIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta_Funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_Pesquisar;
    private javax.swing.JLabel Jlbl_CPF;
    private javax.swing.JLabel Jlbl_Nome;
    private javax.swing.JLabel Jlbl_Tel;
    private javax.swing.JTextField Jtxtf_Consulta_FuncionarioByID;
    private javax.swing.JTextField Jtxtf_Retorno_CPF;
    private javax.swing.JTextField Jtxtf_Retorno_Nome;
    private javax.swing.JTextField Jtxtf_Retorno_Tel;
    // End of variables declaration//GEN-END:variables
}
