package com.mycompany.crud;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author r.nunes
 */
public class READ extends javax.swing.JFrame {

    /**
     * Creates new form ExibirOcultar
     */
    public READ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jlbl_Exibir = new javax.swing.JLabel();
        Jlbl_Ocultar = new javax.swing.JLabel();
        Jbtn_Exibir = new javax.swing.JButton();
        Jbtn_Ocultar = new javax.swing.JButton();
        Jlbl_Title = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jRadioButton = new javax.swing.JRadioButton();
        jCheckBox = new javax.swing.JCheckBox();
        Jbtn_MostrarJrdb_Ou_Jckb = new javax.swing.JButton();
        Jbtn_MostrarJcbx = new javax.swing.JButton();
        Jlbl_RetornoSelecionado = new javax.swing.JLabel();
        Jlbl_RetornoNaoSelecionado = new javax.swing.JLabel();
        Jlbl_retornoJcbx = new javax.swing.JLabel();
        Jtxtf_Consultr_raAluno = new javax.swing.JTextField();
        Jbtn_queryWhere_raAluno = new javax.swing.JButton();
        Jlbl_retornoNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jlbl_Exibir.setText("Conectado");
        getContentPane().add(Jlbl_Exibir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 60, -1));

        Jlbl_Ocultar.setText("Não conectado");
        getContentPane().add(Jlbl_Ocultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, 30));

        Jbtn_Exibir.setBackground(new java.awt.Color(51, 153, 0));
        Jbtn_Exibir.setText("Exibir");
        Jbtn_Exibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_ExibirActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Exibir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        Jbtn_Ocultar.setBackground(new java.awt.Color(153, 0, 0));
        Jbtn_Ocultar.setText("Ocultar");
        Jbtn_Ocultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_OcultarActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_Ocultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        Jlbl_Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Jlbl_Title.setText("Servidor");
        getContentPane().add(Jlbl_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        getContentPane().add(jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 130, -1));

        jRadioButton.setText("jRadioButton1");
        getContentPane().add(jRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, -1));

        jCheckBox.setText("jCheckBox1");
        jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, -1));

        Jbtn_MostrarJrdb_Ou_Jckb.setText("Mostrar");
        Jbtn_MostrarJrdb_Ou_Jckb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_MostrarJrdb_Ou_JckbActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_MostrarJrdb_Ou_Jckb, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, -1, -1));

        Jbtn_MostrarJcbx.setText("Mostrar");
        Jbtn_MostrarJcbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_MostrarJcbxActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_MostrarJcbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        Jlbl_RetornoSelecionado.setText("jLabel1");
        getContentPane().add(Jlbl_RetornoSelecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        Jlbl_RetornoNaoSelecionado.setText("jLabel2");
        getContentPane().add(Jlbl_RetornoNaoSelecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        Jlbl_retornoJcbx.setText("jLabel3");
        getContentPane().add(Jlbl_retornoJcbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));
        getContentPane().add(Jtxtf_Consultr_raAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 70, -1));

        Jbtn_queryWhere_raAluno.setText("Buscar");
        Jbtn_queryWhere_raAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_queryWhere_raAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_queryWhere_raAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, -1, -1));

        Jlbl_retornoNome.setText("-----");
        getContentPane().add(Jlbl_retornoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 70, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Connection connection = null;
        PreparedStatement statement = null;
        
        String url = "jdbc:mysql://localhost:3306/escola";
        String user = "root";
        String psswrd = "";
        
        Jlbl_Exibir.setVisible(false);
        Jlbl_Title.setVisible(true);
        Jlbl_Ocultar.setVisible(false);
        Jbtn_Exibir.setVisible(true);
        Jbtn_Ocultar.setVisible(false);
        
        Jlbl_RetornoNaoSelecionado.setVisible(false);
        Jlbl_retornoJcbx.setVisible(false);
        Jlbl_RetornoSelecionado.setVisible(false);
        
    }//GEN-LAST:event_formWindowOpened

    private void Jbtn_ExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_ExibirActionPerformed
        // TODO add your handling code here:
        Jlbl_Exibir.setVisible(true);
        Jlbl_Title.setVisible(true);
        Jlbl_Ocultar.setVisible(false);
        Jbtn_Exibir.setVisible(false);
        Jbtn_Ocultar.setVisible(true);
    }//GEN-LAST:event_Jbtn_ExibirActionPerformed

    private void Jbtn_OcultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_OcultarActionPerformed
        // TODO add your handling code here:
        Jlbl_Exibir.setVisible(false);
        Jlbl_Title.setVisible(true);
        Jlbl_Ocultar.setVisible(true);
        Jbtn_Exibir.setVisible(true);
        Jbtn_Ocultar.setVisible(false);
    }//GEN-LAST:event_Jbtn_OcultarActionPerformed

    private void jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxActionPerformed

    private void Jbtn_MostrarJrdb_Ou_JckbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_MostrarJrdb_Ou_JckbActionPerformed
        // TODO add your handling code here:
        boolean rdbSelecionado = jRadioButton.isSelected();
        boolean ckbSelecionado = jCheckBox.isSelected();
        
        if (rdbSelecionado){
            Jlbl_RetornoSelecionado.setText("RadioButton: " + rdbSelecionado);
            Jlbl_RetornoNaoSelecionado.setText("CheckButton: " + ckbSelecionado);
        } else {
            Jlbl_RetornoSelecionado.setText("CheckButton: " + ckbSelecionado);
            Jlbl_RetornoNaoSelecionado.setText("RadioButton: " + rdbSelecionado);
        }
        
        Jlbl_RetornoSelecionado.setVisible(true);
        Jlbl_RetornoNaoSelecionado.setVisible(true);
    }//GEN-LAST:event_Jbtn_MostrarJrdb_Ou_JckbActionPerformed

    private void Jbtn_MostrarJcbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_MostrarJcbxActionPerformed
        // TODO add your handling code here:
        String select = (String) jComboBox.getSelectedItem();
        
        Jlbl_retornoJcbx.setText("CheckBox Selecionado: " + select);
        Jlbl_retornoJcbx.setVisible(true);
    }//GEN-LAST:event_Jbtn_MostrarJcbxActionPerformed

    private void Jbtn_queryWhere_raAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_queryWhere_raAlunoActionPerformed
        // TODO add your handling code here:
        Connection connection = null;
        PreparedStatement statement = null;
        
        String url = "jdbc:mysql://localhost:3306/escola";
        String user = "root";
        String psswrd = "";
        
        
        try {
            connection = DriverManager.getConnection(url, user, psswrd);
            String query = "SELECT nome FROM aluno";
            statement = connection.prepareStatement(query);
            
            ResultSet resultSet = statement.executeQuery();
            
            if(resultSet.next()){
                String nome = resultSet.getString("nome");
                Jlbl_retornoNome.setText(nome);
            }
            else {
                Jlbl_retornoNome.setText("Aluno não encontrado");
            }
            
            resultSet.close();
            statement.close();
            connection.close();
            
        } catch (SQLException erro) {
            System.out.println("Erro: " + erro);
        }
    }//GEN-LAST:event_Jbtn_queryWhere_raAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(READ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(READ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(READ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(READ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new READ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_Exibir;
    private javax.swing.JButton Jbtn_MostrarJcbx;
    private javax.swing.JButton Jbtn_MostrarJrdb_Ou_Jckb;
    private javax.swing.JButton Jbtn_Ocultar;
    private javax.swing.JButton Jbtn_queryWhere_raAluno;
    private javax.swing.JLabel Jlbl_Exibir;
    private javax.swing.JLabel Jlbl_Ocultar;
    private javax.swing.JLabel Jlbl_RetornoNaoSelecionado;
    private javax.swing.JLabel Jlbl_RetornoSelecionado;
    private javax.swing.JLabel Jlbl_Title;
    private javax.swing.JLabel Jlbl_retornoJcbx;
    private javax.swing.JLabel Jlbl_retornoNome;
    private javax.swing.JTextField Jtxtf_Consultr_raAluno;
    private javax.swing.JCheckBox jCheckBox;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JRadioButton jRadioButton;
    // End of variables declaration//GEN-END:variables
}
